version: "3"

services:
  postgres:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=student
      - POSTGRES_PASSWORD=studentpassword
      - POSTGRES_DB=footballCoach
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - external

volumes:
  postgres-data2:
    driver: local
  db_data:
    driver: local

networks:
  wpsite:
  external:
    driver: bridge
