version: "3"

services:
  mysql:
    image: mysql:8.0
    ports:
      - 3380:3306
    environment:
      - MYSQL_DATABASE=footballCoach
      - MYSQL_USER=student
      - MYSQL_PASSWORD=studentpassword
      - MYSQL_ROOT_PASSWORD=rootpassword

volumes:
  mysql_data:
    driver: local