version: "3"

services:
  # backend: 
  #   image: footbalcoach_backend
  #   build:
  #      context: ./football-coach-backend
  #      dockerfile: Dockerfile.backend
  #     - ./football-coach-backend
  #   ports:
  #     - 3000:3000
  
  # frontend:
  #   image: footbalcoach_frontend
  #   build:
  #      context: ./football-coach-frontend
  #      dockerfile: Dockerfile.frontend
  #   ports:
  #     - 3001:3000

  postgres:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=student
      - POSTGRES_PASSWORD=studentpassword
      - POSTGRES_DB=footballCoach
    ports:
      - '5432:5432'
    volumes: 
      - ./postgres-data2:/var/lib/postgresql/data
    networks:
      - external

volumes:
  postgres-data2:
    driver: local

networks:
  external:
    driver: bridge